Update 2025-02-21 20:59

diff --git a/.github/Record/Build.yml b/.github/Record/Build.yml
--- a/.github/Record/Build.yml
+++ b/.github/Record/Build.yml
@@ -79,7 +79,17 @@ jobs:
                 curl -f -L "$url" >> Tool-repo/Ruleset/ProxyGFW.list || { echo "Download Failed: $url"; exit 1; }
                 echo "" >> Tool-repo/Ruleset/ProxyGFW.list
             done
-            # 下载规则
+            # 合并 AI 规则
+            urls=(
+                "https://ruleset.skk.moe/List/non_ip/ai.conf"
+                "https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Custom/xAI.list"
+            )
+            > Tool-repo/Ruleset/AI.list
+            for url in "${urls[@]}"; do
+                echo "Downloading: $url"
+                curl -f -L "$url" >> Tool-repo/Ruleset/AI.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/AI.list
+            done            # 下载规则
             files=(
                 # 苹果
                 "APNs.list https://kelee.one/Tool/Loon/Rule/ApplePushNotificationService.list"
@@ -93,7 +103,7 @@ jobs:
                 # AI
                 "OpenAI.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"
                 "Claude.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list"
-                "AI.list https://ruleset.skk.moe/List/non_ip/ai.conf"
+                "xAI.list https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Custom/xAI.list"
                 # 社交媒体
                 "Twitter.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list"
                 "Instagram.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list"
