Update Fork.yml

diff --git a/.github/workflows/Fork.yml b/.github/workflows/Fork.yml
--- a/.github/workflows/Fork.yml
+++ b/.github/workflows/Fork.yml
@@ -280,25 +280,20 @@ jobs:
         done
     
     - name: 提取链接
-      if: env.LOON_SWITCH == 'true'  # 添加开关条件
+      if: env.LOON_SWITCH == 'true'
       run: |
-        mkdir -p Tool-repo/Loon/Plugin
         mkdir -p Tool-repo/Loon/Script
-        cd Tool-repo/Loon/Plugin  # 进入 Plugin 目录
+        cd Tool-repo/Loon/Plugin
         for file in *.plugin; do
           if [ "$file" ] ; then
-            # 查找是否存在 https://kelee.one/Resource/Script/ 链接
-            grep -o 'https://kelee\.one/Resource/Script/[^ ]*' "$file" | while read -r script_url; do
-              
-              # 提取脚本名称
+            # 只提取以 .js 结尾的脚本链接
+            grep -o 'https://kelee\.one/Resource/Script/[^ ]*\.js' "$file" | while read -r script_url; do
               script_name=$(basename "$script_url")
-              
-              # 下载对应的 JS 文件
-              curl -A "Surge iOS/3367" -L -o "../Script/$script_name" "$script_url"
-              
+              curl -A "Surge iOS/3367" -L -o "../Script/$script_name" "$script_url" || echo "Failed to download $script_url" >> error.log
             done
           fi
         done
+
 
     - name: 编辑LOON模块
       if: env.LOON_SWITCH == 'true'  # 添加开关条件
